version: "3"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9080:9080
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.listen-address=:9080"
      - "--web.enable-admin-api"
    networks:
      - grafanadocker
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_logs:/var/log/grafana
    depends_on:
      - prometheus
    networks:
      - grafanadocker
  remix-app:
    container_name: grafana-remix-app
    image: grafana-remix-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - grafana
    networks:
      - grafanadocker
volumes:
  grafana_data:
  grafana_logs:
  prometheus:
networks:
  grafanadocker:
