global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9080"]

  - job_name: "grafana-app"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:8080"]
